<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_second_level_cache.logger_chain' shared service.

$this->services['doctrine.orm.default_second_level_cache.logger_chain'] = $instance = new \Doctrine\ORM\Cache\Logging\CacheLoggerChain();

$instance->setLogger('statistics', new \Doctrine\ORM\Cache\Logging\StatisticsCacheLogger());

return $instance;
