<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.default_second_level_cache.logger_statistics' shared service.

return $this->services['doctrine.orm.default_second_level_cache.logger_statistics'] = new \Doctrine\ORM\Cache\Logging\StatisticsCacheLogger();
